version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ec2-user/acebook/
hooks:
  BeforeInstall:
    - location: scripts/install-dependencies
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start-server
      timeout: 300 
      runas: root