#!/bin/bash
yum update 
curl -sL https://rpm.nodesource.com/setup_18.x | bash -
yum install -y nodejs
cat > /etc/yum.repos.d/mongodb-org-5.0.repo <<EOL
[mongodb-org-5.0]
name=MongoDB Repository
baseurl=https://repo.mongodb.org/yum/amazon/2/mongodb-org/5.0/x86_64/
gpgcheck=1
enabled=1
gpgkey=https://www.mongodb.org/static/pgp/server-5.0.asc
...
EOL
yum install -y mongodb-org
systemctl start mongod