#!/bin/bash
yum update 
curl -sL https://rpm.nodesource.com/setup_18.x | bash -
yum install -y nodejs
yum install openssl10
yum install openssl10-libs
cat > /etc/yum.repos.d/mongodb-org-6.0.repo <<EOL
[mongodb-org-6.0]
name=MongoDB Repository
baseurl=https://repo.mongodb.org/yum/amazon/2/mongodb-org/6.0/x86_64/
gpgcheck=1
enabled=1
gpgkey=https://www.mongodb.org/static/pgp/server-6.0.asc
EOL
yum install -y mongodb-org
sudo systemctl start mongod