#!/bin/bash
yum update 
curl -sL https://rpm.nodesource.com/setup_18.x | bash -
yum install -y nodejs
cat > /etc/yum.repos.d/mongodb-org-8.0.repo <<EOL
[mongodb-org-8.0]
name=MongoDB Repository
baseurl=https://repo.mongodb.org/yum/amazon/2023/mongodb-org/8.0/x86_64/
gpgcheck=1
enabled=1
gpgkey=https://pgp.mongodb.com/server-8.0.asc
EOL
yum install -y mongodb-org
systemctl start mongod 